version: '3.3'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: sqlcmd -S db1.internal.prod.example.com -U SA -P '' -Q 'select 1'
    networks:
      mynetwork:
        aliases:
          - db1.internal.prod.example.com

  web:
    build: .
    user: root
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code/
    ports:
      - "8080:8000"
    environment:
      DJANGO_SETTINGS_MODULE: djangosite.settings
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    networks:
      mynetwork:
        aliases:
          - web1.internal.prod.example.com

networks:
  mynetwork:
    driver: bridge