# Generated by Django 3.0 on 2023-01-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('CPU', models.IntegerField(default=0)),
                ('RAM', models.FloatField(default=0)),
                ('Memory', models.IntegerField(default=0)),
            ],
        ),
    ]
