# Generated by Django 3.0 on 2023-01-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('Bindings', models.CharField(max_length=255, verbose_name='Bindings')),
                ('state', models.CharField(max_length=255, verbose_name='state')),
            ],
            options={
                'verbose_name_plural': 'Sites',
            },
        ),
    ]
