# Generated by Django 3.0 on 2023-01-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('MonitorId', models.AutoField(primary_key=True, serialize=False)),
                ('ServerName', models.CharField(blank=True, max_length=50, verbose_name='ServerName')),
                ('Name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('State', models.CharField(blank=True, max_length=50, verbose_name='State')),
                ('Monitor', models.CharField(blank=True, choices=[('On', 'On'), ('Off', 'Off')], default='Off', max_length=20, verbose_name='Monitor')),
                ('Notifications', models.BooleanField(default=False, verbose_name='Notifications')),
            ],
        ),
    ]
