# Generated by Django 3.0 on 2023-01-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('State', models.CharField(blank=True, max_length=200)),
                ('Bindings', models.CharField(blank=True, max_length=200)),
                ('ServerName', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Notifications', models.BooleanField(default=False)),
            ],
        ),
    ]
